version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DATABASE: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data

  app:
    image: sophialj/flask-todo-app:latest
    command: "sh /scripts/run.sh"
    environment:
      FLASK_APP: app.py
      FLASK_DEBUG: 1
    depends_on:
      - postgres
    volumes:
      - ./app:/app

volumes:
  postgres:
